spring:
  profiles: dev
jdbc:
  driverClassName: "org.h2.Driver"
  url: "jdbc:h2:mem:registration_02;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE"
  user: "sa"
  pass: ""
  init-db: false
hibernate:
  dialect: "org.hibernate.dialect.H2Dialect"
  show_sql: true
  hbm2ddl:
    auto: "create-drop"
